## NUMPY
- SHORT OF NUMERICAL PYTHON
- FOUNDATIONAL PACKAGE FOR NUMERICAL COMPUTING IN PYTHON
- PROVIDES NDARRAYS OBJECT WHICH IS AN EFFICIENT MULTIDIMENSIONAL ARRAY PROVIDING FAST ARRAY ORIENTED
  OPERATIONS
- PROVIDES A LOT OF FUNCTIONS.

In [8]:
import numpy as np

## CREATING ND ARRAYS
- CREATING NDARRAYS FROM AN OBJECT

In [9]:
l1 = [1,2,3,4,5]
a1 = np.array(l1)
a1

array([1, 2, 3, 4, 5])

In [10]:
type(a1)

numpy.ndarray

In [11]:
t1 = (1,2,3,4,5)
a1 = np.array(t1)
a1

array([1, 2, 3, 4, 5])

In [12]:
a1 = np.array(range(2,11,2))
a1

array([ 2,  4,  6,  8, 10])

In [13]:
a1.ndim

1

In [14]:
a1.shape

(5,)

In [15]:
a1 = np.array([[1,2,3],[4,5,6]])
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
a1.ndim

2

In [17]:
a1.shape

(2, 3)

In [18]:
a1 = np.array([[[1,2,3],[4,5,6]]])
a1

array([[[1, 2, 3],
        [4, 5, 6]]])

In [19]:
a1.ndim

3

In [20]:
a1.shape

(1, 2, 3)

In [21]:
a1 = np.array([[[[1,2,3],[4,5,6]]]])
a1

array([[[[1, 2, 3],
         [4, 5, 6]]]])

In [22]:
a1.ndim

4

In [23]:
a1.shape

(1, 1, 2, 3)

In [24]:
a1 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
a1

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [25]:
a1.ndim

3

In [26]:
a1.shape

(2, 2, 2)

In [27]:
a1 = np.array([[[1,2],[3,4],[5,6],[7,8]]])
a1

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [28]:
a1.ndim


3

In [29]:
a1.shape


(1, 4, 2)

## CREATING NDARRAYS OF ONES,ZEROES AND SPECIFIC VALUES

In [30]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
np.ones((5,5), dtype = int)


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [24]:
np.ones((3,2,4))


array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [27]:
np.full((4,5), fill_value= 5)


array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [28]:
np.eye(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## OPERATIONS ON NDARRAYS

In [29]:
l = [1,2,3,4,5]
l + 2

TypeError: can only concatenate list (not "int") to list

In [30]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [31]:
a + 2

array([3, 4, 5, 6, 7])

In [32]:
b = np.array([4,5,6,7,8])
b

array([4, 5, 6, 7, 8])

In [33]:
a + b


array([ 5,  7,  9, 11, 13])

In [34]:
a - b


array([-3, -3, -3, -3, -3])

In [35]:
a*b


array([ 4, 10, 18, 28, 40])

In [36]:
a/b


array([0.25      , 0.4       , 0.5       , 0.57142857, 0.625     ])

In [37]:
b/a


array([4.  , 2.5 , 2.  , 1.75, 1.6 ])

In [38]:
a%2


array([1, 0, 1, 0, 1])

In [39]:
a > b 


array([False, False, False, False, False])

## INDEXING AND SLICING IN SINGLE DIMENSION ARRAY

In [40]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
a[7]


np.int64(7)

In [43]:
a[-1]


np.int64(9)

In [44]:
a[-10]


np.int64(0)

In [45]:
a[::-1]


array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [46]:
a[-3:-7:3]


array([], dtype=int64)

## RESHAPE AND TRANSPOSE

In [47]:
a = np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [48]:
a.ndim


1

In [49]:
a.shape


(16,)

In [50]:
a = a.reshape((4,4))
a
              

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [51]:
a = a.reshape((8,2))
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [52]:
a = a.reshape((2,8))
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [53]:
a = a.reshape((2,2,2,2))
a

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [54]:
a = np.arange(16).reshape((4,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [55]:
a.T


array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

## ONE DIMENSIONAL ARRAY

## Functions

In [2]:
a = np.array([2,3,6,8,9,4,5,1,7])
a

array([2, 3, 6, 8, 9, 4, 5, 1, 7])

In [3]:
a.sort()

In [4]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.square(a)

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [6]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [7]:
np.cbrt(a)

array([1.        , 1.25992105, 1.44224957, 1.58740105, 1.70997595,
       1.81712059, 1.91293118, 2.        , 2.08008382])

In [8]:
np.abs([-1,-2,4,-5,6,-8])

array([1, 2, 4, 5, 6, 8])

In [9]:
np.add([1,2,3],[4,5,6])

array([5, 7, 9])

In [10]:
np.subtract([1,2,3],[4,5,6])

array([-3, -3, -3])

In [11]:
np.multiply([1,2,3],[4,5,6])

array([ 4, 10, 18])

In [12]:
np.divide([1,2,3],[4,5,6])

array([0.25, 0.4 , 0.5 ])

In [15]:
a1=np.array([2,1,3,6,3,4])
a2=np.array([3,4,2,5,8,5])

In [16]:
np.minimum(a1,a2)

array([2, 1, 2, 5, 3, 4])

In [17]:
np.maximum(a1,a2)

array([3, 4, 3, 6, 8, 5])

In [18]:
np.greater(a1,a2)

array([False, False,  True,  True, False, False])

In [19]:
np.greater(a2,a1)

array([ True,  True, False, False,  True,  True])

In [20]:
np.less(a2,a1)

array([False, False,  True,  True, False, False])

In [21]:
np.less(a1,a2)

array([ True,  True, False, False,  True,  True])

In [22]:
a1 = np.arange(21)

In [23]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [24]:
a1.mean()

np.float64(10.0)

In [25]:
np.median(a1)

np.float64(10.0)

In [26]:
a1.min()

np.int64(0)

In [27]:
a1.max()

np.int64(20)

In [28]:
a1.sum()

np.int64(210)

## TWO DIMENSIONAL ARRAY

In [29]:
a = np.arange(64).reshape(8,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [30]:
a.shape

(8, 8)

In [31]:
a.mean()

np.float64(31.5)

In [32]:
a.mean(axis=0)                              # Taking values columnwise (Top to Bottom) (vertically on axis)

array([28., 29., 30., 31., 32., 33., 34., 35.])

In [33]:
a.mean(axis=1)                              # Taking values rowwise (left to right)

array([ 3.5, 11.5, 19.5, 27.5, 35.5, 43.5, 51.5, 59.5])

In [34]:
a.max()

np.int64(63)

In [36]:
a.max(axis=1)

array([ 7, 15, 23, 31, 39, 47, 55, 63])

In [37]:
a.max(axis=0)

array([56, 57, 58, 59, 60, 61, 62, 63])

In [38]:
a.min()

np.int64(0)

In [39]:
a.min(axis=0)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [40]:
a.min(axis=1)

array([ 0,  8, 16, 24, 32, 40, 48, 56])

In [41]:
x=np.array([1,2,4,3,3,4])
x

array([1, 2, 4, 3, 3, 4])

In [42]:
np.argmax(x)

np.int64(2)

In [43]:
np.argmin(x)

np.int64(0)

In [32]:
a = np.arange(9).reshape((3,3))
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
np.argmax(a)

np.int64(8)

In [34]:
np.argmin(a)

np.int64(0)

In [35]:
np.argmax(a,axis=0)

array([2, 2, 2])

In [36]:
np.argmax(a,axis=1)

array([2, 2, 2])

In [44]:
a=np.array([2,1,5,4,3,5,6,7,3,9,2,3]).reshape(3,4)

In [45]:
a

array([[2, 1, 5, 4],
       [3, 5, 6, 7],
       [3, 9, 2, 3]])

In [46]:
np.argmax(a)

np.int64(9)

In [47]:
np.argmax(a,axis=0)

array([1, 2, 1, 1])

In [48]:
np.argmax(a,axis=1)

array([2, 3, 1])

In [49]:
a1=a.reshape(1,3,4)

In [50]:
a

array([[2, 1, 5, 4],
       [3, 5, 6, 7],
       [3, 9, 2, 3]])

In [51]:
a1.squeeze()
a1

array([[[2, 1, 5, 4],
        [3, 5, 6, 7],
        [3, 9, 2, 3]]])

In [52]:
a2=a1.squeeze()              # 2D
a2

array([[2, 1, 5, 4],
       [3, 5, 6, 7],
       [3, 9, 2, 3]])

In [53]:
a1=np.arange(5)
a2=np.arange(5,10)
print(a1)
print(a2)

[0 1 2 3 4]
[5 6 7 8 9]


In [54]:
a1

array([0, 1, 2, 3, 4])

In [55]:
np.concatenate((a1,a2))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
np.concatenate((a2,a1))

array([5, 6, 7, 8, 9, 0, 1, 2, 3, 4])

In [57]:
a1=a1.reshape(1,5)
a1

array([[0, 1, 2, 3, 4]])

In [58]:
a2=a2.reshape(1,5)

In [59]:
a2

array([[5, 6, 7, 8, 9]])

In [60]:
np.concatenate((a2,a1),axis=0)

array([[5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4]])

In [61]:
np.concatenate((a2,a1),axis=1)

array([[5, 6, 7, 8, 9, 0, 1, 2, 3, 4]])

### RANDOM NUMBERS

In [69]:
np.random.randint(1,100)

68

In [70]:
np.random.randint(1,100,10)

array([41, 36, 54, 38,  8, 78, 64, 27, 46, 36], dtype=int32)

In [72]:
np.random.randint(1,100,(10,10))

array([[21, 45, 25, 27, 12, 66, 52,  6, 34, 97],
       [23, 45, 87, 92,  6, 86, 92, 14, 75, 57],
       [38, 84, 15, 95, 67, 19, 13,  9, 32, 18],
       [63,  1, 91,  1, 38, 13, 49, 60, 76, 32],
       [59, 43, 22, 46, 94, 50, 54, 56, 88, 38],
       [18, 88, 58, 71,  1, 84, 91, 92, 55, 18],
       [92, 18, 32,  3, 92, 90, 52, 52, 59, 51],
       [90, 38, 30, 37, 62, 84, 25, 80,  1, 94],
       [34, 79, 21, 24, 29, 53,  9, 61, 16, 16],
       [ 9, 38, 11, 94, 43, 23, 25, 79, 26, 16]], dtype=int32)

In [73]:
np.random.rand(10)

array([0.98308008, 0.1629668 , 0.52849297, 0.66563864, 0.21874414,
       0.2675817 , 0.67666445, 0.88302426, 0.55065213, 0.71181535])

In [74]:
np.random.rand(10,5)

array([[0.55651881, 0.44508331, 0.94116415, 0.69008067, 0.52783419],
       [0.40851104, 0.76504439, 0.89776209, 0.55914295, 0.06690392],
       [0.89129356, 0.00267249, 0.00379515, 0.59474556, 0.75833043],
       [0.33568787, 0.21777476, 0.50339873, 0.45043871, 0.64141831],
       [0.5959497 , 0.6822738 , 0.88638404, 0.20990929, 0.33449916],
       [0.32718735, 0.14169746, 0.91680786, 0.27800527, 0.00420858],
       [0.45402938, 0.21349356, 0.72606529, 0.85721371, 0.1907113 ],
       [0.50611886, 0.17266794, 0.33870726, 0.32587439, 0.18291242],
       [0.9912385 , 0.28836691, 0.71361341, 0.61820397, 0.36289725],
       [0.62106104, 0.87046826, 0.39532282, 0.79458716, 0.65158384]])

In [75]:
np.random.randn(10)

array([-0.17321333,  1.32754261, -1.00418036,  1.52482698,  0.34534853,
        0.81895921, -0.59618767, -2.31077361,  0.28430614,  0.80857608])

In [76]:
np.random.randn(10,5)

array([[ 3.23342790e-01,  5.60687666e-02,  3.46877551e-01,
         7.15612399e-01,  2.23858718e+00],
       [-8.00842694e-01, -1.06099366e+00, -4.99851534e-01,
         2.94927592e-01,  1.22206831e-01],
       [ 3.44105584e-01,  1.43155121e+00, -1.04896449e+00,
        -2.11566788e+00,  7.58687121e-01],
       [-6.39995179e-02, -1.28939254e-01, -1.14431468e+00,
         5.70990396e-01, -5.85276509e-01],
       [ 2.83328511e-01,  7.56381003e-01,  5.40507583e-01,
         8.46199272e-01,  2.43902246e-01],
       [ 2.55739881e-05, -1.39263910e+00, -8.48547187e-01,
         4.12047682e-02, -1.01636184e+00],
       [-1.26519930e+00, -1.30044749e+00,  1.09656717e-01,
        -1.54765885e+00, -4.50472509e-01],
       [ 4.75824407e-01, -3.11054499e-02,  1.58097015e+00,
         4.16801636e-02,  3.44990500e-01],
       [ 2.89237684e-01, -1.37632422e+00,  2.95407044e-01,
        -9.44250875e-02,  3.50099079e-01],
       [-1.14263252e+00, -3.31029787e-01, -1.19135200e+00,
        -1.26181268e+00

## CONDITIONAL INDEXING

In [77]:
a = np.random.randint(1,100,(8,8))
a

array([[17, 15, 60, 19, 66, 67, 85, 68],
       [46, 49, 23, 43, 84, 61, 66, 82],
       [69, 11, 12, 21, 47, 19, 86, 92],
       [30, 21, 71, 43, 65, 26, 89, 87],
       [44,  1, 77, 31, 52, 83, 90,  1],
       [26,  1, 11, 99, 53, 44, 78, 79],
       [44, 33, 38, 72, 78, 73, 67, 60],
       [ 4,  9, 90, 44,  9, 92, 42, 92]], dtype=int32)

In [78]:
a>50

array([[False, False,  True, False,  True,  True,  True,  True],
       [False, False, False, False,  True,  True,  True,  True],
       [ True, False, False, False, False, False,  True,  True],
       [False, False,  True, False,  True, False,  True,  True],
       [False, False,  True, False,  True,  True,  True, False],
       [False, False, False,  True,  True, False,  True,  True],
       [False, False, False,  True,  True,  True,  True,  True],
       [False, False,  True, False, False,  True, False,  True]])

In [79]:
a[a>50]

array([60, 66, 67, 85, 68, 84, 61, 66, 82, 69, 86, 92, 71, 65, 89, 87, 77,
       52, 83, 90, 99, 53, 78, 79, 72, 78, 73, 67, 60, 90, 92, 92],
      dtype=int32)

In [80]:
a[a<50]

array([17, 15, 19, 46, 49, 23, 43, 11, 12, 21, 47, 19, 30, 21, 43, 26, 44,
        1, 31,  1, 26,  1, 11, 44, 44, 33, 38,  4,  9, 44,  9, 42],
      dtype=int32)

## SLICING IN MULTIDIMENSIONAL ARRAY

In [39]:
a=np.random.randint(1,100,(10,10))
a

array([[55, 61, 78, 39, 46, 49, 97, 32, 51, 10],
       [71, 42,  8, 29, 97, 26,  7, 21, 63, 97],
       [ 7, 11, 82, 63, 32, 38, 17, 70, 99, 82],
       [80, 24, 47, 77, 91, 16, 24, 21, 65, 90],
       [14, 11, 52, 99, 81, 57, 30,  2, 99, 29],
       [56, 38, 12, 25,  3, 27,  6, 60, 42, 26],
       [80, 19, 17, 64, 89, 13, 67,  1, 41, 80],
       [33, 20, 50, 14, 49, 46, 99, 28, 85,  3],
       [24, 96, 59, 63, 83, 17, 39, 23, 27, 78],
       [63, 30, 12, 58, 10, 95, 57, 42, 87, 16]], dtype=int32)

In [40]:
a[1,4]

np.int32(97)

In [41]:
a[1]

array([71, 42,  8, 29, 97, 26,  7, 21, 63, 97], dtype=int32)

In [42]:
a[1][4]

np.int32(97)

In [43]:
a[2:4,:]

array([[ 7, 11, 82, 63, 32, 38, 17, 70, 99, 82],
       [80, 24, 47, 77, 91, 16, 24, 21, 65, 90]], dtype=int32)

In [44]:
a[2:9:1,2:9:1]

array([[82, 63, 32, 38, 17, 70, 99],
       [47, 77, 91, 16, 24, 21, 65],
       [52, 99, 81, 57, 30,  2, 99],
       [12, 25,  3, 27,  6, 60, 42],
       [17, 64, 89, 13, 67,  1, 41],
       [50, 14, 49, 46, 99, 28, 85],
       [59, 63, 83, 17, 39, 23, 27]], dtype=int32)