In [52]:
# numpy follows Zero-Based Indexing

In [53]:
python_list = [1,2,3,4,5]          # diff betn python list[] and np.array([])
print(python_list)

import numpy as np
numpy_array = np.array([1,2,3,4,5])
print(numpy_array)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [2]:
import numpy as np                        # 

temperatures = np.array([32.5,31.8,33.0,35.2,36.6])
average = np.mean(temperatures)
print(average)

33.82


In [3]:
import numpy as np               # 1-D Array: list of numbers in row
ar_1d = np.array([1,2,3,4,5])

print(ar_1d)

[1 2 3 4 5]


In [4]:
import numpy as np              # 2-D Array: Data in Rows and columns
ar_2d = np.array([[1,2,3,],
                 [4,5,6],
                 [7,8,9]])

print(ar_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
# Multi-Dimensional Array       ,matrix is a 2-D array in which nums are stored in rows n columns
import numpy as np

matrix = np.array([[2,4,6],
                  [8,10,12]])
print(matrix)

[[ 2  4  6]
 [ 8 10 12]]


In [7]:
# 3-D Array means stack of multiple 2-D Arrays

In [10]:
# creating arrays from python lists
import numpy as np
arr= np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [11]:
# creating arrays from python lists
import numpy as np
arr= np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [19]:
# with default values
# np.zeros(shape) (3) for 1d,(3,3) 2d
import numpy as np
zeroes_array = np.zeros(3)
zeroes_array

array([0., 0., 0.])

In [21]:
# with default values
# np.zeros(shape) (3) for 1d,(3,3) for 2d.
import numpy as np
zeroes_array = np.zeros((3,3))
print(zeroes_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
# all elements start with one in an array
import numpy as np
ones_array = np.ones((2,3))
print(ones_array)


[[1. 1. 1.]
 [1. 1. 1.]]


In [22]:
# full(shape, value): to create an array to start with a specific number or value
import numpy as np
filled_array = np.full((2,2),7)
filled_array

array([[7, 7],
       [7, 7]])

In [23]:
# Create sequences of numbers in numpy
# arange()
#arange(start,stop,step)
import numpy as np
arr = np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])

In [24]:
# creating identity matrices
#eye(size)
import numpy as np

identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
#Shape
import numpy as np

arr_2D = np.array([[1,2,3],[4,5,6]])
arr_2D

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
#Shape: shows(rows,columns)
import numpy as np

arr_2D = np.array([[1,2,3],[4,5,6]])
arr_2D.shape

(2, 3)

In [28]:
#Size: total numbs of elements in array

import numpy as np
arr = np.array([[10,20,30],[40,50,60]])
arr.size

6

In [30]:
# ndim: to check no. of dimensions
import numpy as np
arr_1d = np.array([1,2,3])
arr_2D = np.array([[1,2],[3,4],[5,6],[7,8]])
arr_3D = np.array([[[1,2],[3,4],[5,6],[7,8]]])

print(arr_1d.ndim)
print(arr_2D.ndim)
print(arr_3D.ndim)

1
2
3


In [38]:
# dtype: datatypes of elements
import numpy as np

arr= np.array([True])
arr.dtype

dtype('bool')

In [39]:
# dtype: datatypes of elements
import numpy as np

arr= np.array([1,2.5,True])
arr.dtype

dtype('float64')

In [40]:
# dtype: datatypes of elements
import numpy as np

arr= np.array([1,True])
arr.dtype

dtype('int64')

In [43]:
# astype(newtype): to change datatype to another datatype
import numpy as np

arr = np.array([1.2,2.5,3,7])

int_arr = arr.astype(int)

print(int_arr)
print(int_arr.dtype)
print(int_arr.astype)

[1 2 3 7]
int64
<built-in method astype of numpy.ndarray object at 0x0000020EF6BB34B0>


In [45]:
# astype(newtype): to change datatype to another datatype
import numpy as np

arr = np.array([1.2,2.5,3,7])
print(arr.dtype)
int_arr = arr.astype(int)

print(int_arr)
print(int_arr.dtype)


float64
[1 2 3 7]
int64


In [48]:
# operations
import numpy as np
arr = np.array([10,20,30])

print(arr + 5)
print(arr - 5)
print(arr * 5)
print(arr ** 2)

[15 25 35]
[ 5 15 25]
[ 50 100 150]
[100 400 900]


In [49]:
# Aggregation Function: To find summary of data
# 1. np.sum(array) - Add all
# 2. np.mean(array) - calculate average
# 3. min(array) - min element of array
# 4. max(array) - max element
# 5. np.std(array) - standard deviation calculate
# 6. np.var(array) - variance calculate

In [50]:
import numpy as np

arr = np.array([10,20,30,40,50])
print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))
print(np.var(arr))

150
30.0
10
50
14.142135623730951
200.0


In [51]:
# Indexing and Slicing - Pick only single element and Pick a portion of elements
# Fancy Indexing - to select multiple elemnts at once, using a list of indices
# Boolean Masking - to filter elements according to conditions and returns values which fulfils condition

In [57]:
# to access specific element in array
#array[index] - 1D array
#array[row,column] - 2D array
import numpy as np
arr = np.array([10,20,30,40,50])
print(arr[0]) #first element
print(arr[2]) #30
print(arr[-1]) #last element
#print(arr[10])

10
30
50


In [63]:
#Slicing
#array(start:stop:step)

import numpy as np
arr = np.array([10,20,30,40,50,60])
print(arr[0:6])  #index 0 to 5
print(arr[:-1])   #index 0 to 3
print(arr[::2])  #every second element
print(arr[::-1])  #reverse array

[10 20 30 40 50 60]
[10 20 30 40 50]
[10 30 50]
[60 50 40 30 20 10]


In [64]:
# Fancy indexing: creates copy of data, original data is not modified
import numpy as np
arr = np.array([10,20,30,40,50,60])
print(arr[[0,2,4]])

[10 30 50]


In [65]:
# Boolean Masking: used instead of loops
import numpy as np
arr = np.array([10,20,30,40,50,60])
print(arr[arr > 25])

[30 40 50 60]


In [67]:
''' Reshaping and Manipulating Arrays: 
    Reshape: to change shape(dimensions(rows,columns)) of array without modifying its data,
    
'''
# reshape(rows,columns) specify new shape if dimensions match
#Reshape does not create COPY, it returns a VIEW(will affect original array)


[[10 20 30]
 [40 50 60]]


In [2]:
#Reshape
import numpy as np
arr = np.array([10,20,30,40,50,60])
reshaped_Arr = arr.reshape(2,3)     #(rows,columns)
print(reshaped_Arr)

[[10 20 30]
 [40 50 60]]


In [6]:
#Flattening Arrays: to convert multi-dimensional array into 1D Array.
# .ravel() - returns views
# .flatten() - returns copy

import numpy as np
arr_2D = np.array([[1,2,3],[4,5,6]])
print(arr_2D.ravel())
print(arr_2D)
print(arr_2D.flatten())
print(arr_2D)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [12]:
# INSERT 
''' np.insert(array,index,value,axis=None)
    array - original array
    index - position of new value to be inserted
    value - actual data or new value
    axis :- 0, data to be inserted row-wise, for 2D array,
    axis :- 1, column-wise insert
'''  
import numpy as np

arr = np.array([10,20,30,40,50,60])
print(arr)
new_arr = np.insert(arr,2,100)
print(new_arr)

[10 20 30 40 50 60]
[ 10  20 100  30  40  50  60]


In [14]:
# INSERT IN 2D
import numpy as np
arr_2D = np.array([[1,2],[3,4]])
print(arr_2D)
# insert new row at index 1
new_arr_2D = np.insert(arr_2D, 1, [5,6], axis=0)  #row-wise
print(new_arr_2D)

[[1 2]
 [3 4]]
[[1 2]
 [5 6]
 [3 4]]


In [15]:
# INSERT IN 2D
import numpy as np
arr_2D = np.array([[1,2],[3,4]])
print(arr_2D)
# insert new row at index 1
new_arr_2D = np.insert(arr_2D, 1, [5,6], axis=1)   #column-wise
print(new_arr_2D)

[[1 2]
 [3 4]]
[[1 5 2]
 [3 6 4]]


In [17]:
# INSERT IN 2D
import numpy as np
arr_2D = np.array([[1,2],[3,4]])
print(arr_2D)
# insert new row at index 1
new_arr_2D = np.insert(arr_2D, 1, [5,6], axis=None) #single line or 1D array(flatten-array)
print(new_arr_2D)

[[1 2]
 [3 4]]
[1 5 6 2 3 4]


In [18]:
# APPEND
import numpy as np
arr = np.array([10,20,30,40,50,60])
new_arr = np.append(arr,[70,80,90,100])
new_arr

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [23]:
#Concatenate array
'''
np.concatenate((array1,array2), axis=0)
axis 0 > vertical stacking
axis 1 > horizontal stacking
'''
import numpy as np
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])
new_arr = np.concatenate(arr1,arr2)
print(new_arr)

TypeError: only integer scalar arrays can be converted to a scalar index

In [24]:
import numpy as np
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])
new_arr = np.concatenate((arr1,arr2))
print(new_arr)

[10 20 30 40 50 60]


In [27]:
import numpy as np
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])
new_arr = np.concatenate((arr1,arr2), axis=0)
print(new_arr)

[10 20 30 40 50 60]


In [28]:
import numpy as np
arr1 = np.array([10,20,30])
arr2 = np.array([40,50,60])
new_arr = np.concatenate((arr1,arr2), axis=1)
print(new_arr)

AxisError: axis 1 is out of bounds for array of dimension 1

In [30]:
import numpy as np
arr1 = np.array([[10,20,30],[40,50,60]])
arr2 = np.array([[70,80,90],[100,110,120]])
new_arr = np.concatenate((arr1,arr2), axis=1)
print(new_arr)

[[ 10  20  30  70  80  90]
 [ 40  50  60 100 110 120]]


In [32]:
import numpy as np
arr1 = np.array([[10,20,30],[40,50,60]])
arr2 = np.array([[70,80,90],[100,110,120]])
new_arr = np.concatenate((arr1,arr2), axis=0)
print(new_arr)

[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]


In [33]:
#Delete
'''
np.delete(array,index,axis=None)
'''
import numpy as np
arr = np.array([10,20,30,40,50,60])
new_arr = np.delete(arr,0)
print(new_arr)

[20 30 40 50 60]


In [35]:
#2D array
import numpy as np
arr = np.array([[10,20,30,40],[70,80,90,100]])
new_arr = np.delete(arr,0)
print(new_arr)

[ 20  30  40  70  80  90 100]


In [36]:
#2D array
import numpy as np
arr = np.array([[10,20,30,40],[70,80,90,100]])
new_arr = np.delete(arr,0,axis=0)
print(new_arr)

[[ 70  80  90 100]]


In [37]:
#2D array
import numpy as np
arr = np.array([[10,20,30,40],[70,80,90,100]])
new_arr = np.delete(arr,0,axis=1)
print(new_arr)

[[ 20  30  40]
 [ 80  90 100]]


In [42]:
#Splitting
'''
np.split(array, splitting in how many parts)
equal parts split array
np.hsplit()
np.vsplit()
'''
import numpy as np
arr = np.array([10,20,30,40,50,60])

print(np.split(arr,3))

[array([10, 20]), array([30, 40]), array([50, 60])]


In [44]:
import numpy as np
arr = np.array([10,20,30,40,50,60])

print(np.vsplit(arr,3))

ValueError: vsplit only works on arrays of 2 or more dimensions

In [48]:
#BROADCASTING
'''
Broadcasting is a numpy way where you perform operations on various shapes of array,
without using loops.
'''

'\nBroadcasting is a numpy way where you perform operations on various shapes of array,\nwithout using loops.\n'

In [49]:
# WITH LOOP:
prices = [100,200,300]
discount = 10
final_prices = []

for price in prices:
    final_price = price - (price * discount/100)
    final_prices.append(final_price)
print(final_prices)

[90.0, 180.0, 270.0]


In [52]:
# WITHOUT LOOPS: 
import numpy as np
prices = np.array([100,200,300])
discount = 10 # scalar single value
final_prices = prices-(prices * discount/100)

print(final_prices)

[ 90. 180. 270.]


In [54]:
np.array([1,2,3])+10

array([11, 12, 13])

In [55]:
np.array([1,2,3])+[10]

array([11, 12, 13])

In [56]:
np.array([1,2,3])+[10,11]

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [57]:
np.array([1,2,3])+[10,11,12]

array([11, 13, 15])

In [58]:
# Broadcasting without loops
import numpy as np
arr = np.array([1,2,3,4])
result = arr*2
print(result)

[2 4 6 8]


In [59]:
#Broadcasting 1D_Array to 2D_Array:
import numpy as np
matrix = np.array([[1,2,3],[4,5,6]])  #2x3 matrix
vector = np.array([10,20,30])  #1D array

result = matrix + vector
print(result)

[[11 22 33]
 [14 25 36]]


In [60]:
# error in incompatible shapes of array:
import numpy as np
arr1 = np.array([[1,2,3],[4,5,6]]) #shape(2,3)
arr2 = np.array([1,2])  #shape(2,)
result = arr1 + arr2
print(result)

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [63]:
# error in incompatible shapes of array:
import numpy as np
arr1 = np.array([[1,2,3],[4,5,6]]) #shape(2,3)
arr2 = np.array([1,2])  #shape(2,)
arr2.reshape(2,3)
result = arr1 + arr2
print(result)


ValueError: cannot reshape array of size 2 into shape (2,3)

In [64]:
# VECTORIZATION (addition)
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

result = arr1 + arr2
print(result)


[5 7 9]


In [66]:
# VECTORIZATION (multiplication)
import numpy as np
arr = np.array([10,20,30])
multiplied = arr * 3
print(multiplied)

[30 60 90]


In [67]:
'''
Broadcasting:
1. Expands smaller arrays to larger arrays
2. Speed is faster than loops
3. 1D to 2D broadcasting
Vectorization:
1. Applies operation on entire array
2. Faster than loops
3. Matrix operation
'''

'\nBroadcasting:\n1. Expands smaller arrays to larger arrays\n2. Speed is faster than loops\n3. 1D to 2D broadcasting\nVectorization:\n1. Applies operation on entire array\n2. Faster than loops\n3. Matrix operation\n'

In [70]:
# HANDLING MISSING VALUES
'''
1. np.isnan() - detects missing values
2. np.nan_to_num() - to replace missing values from nan to other value
3. np.isinf() - to detect infinite values
'''

'\n1. np.isnan - detects missing values\n2. np.nan_to_num() - to replace missing values from nan to other value\n3. np.isinf() - to detect infinite values\n'

In [72]:
# NAN - NOT A NUMBER, returns Booleaan values

In [73]:
import numpy as np
arr = np.array([1,2,np.nan,4,np.nan,6])
print(np.isnan(arr))


[False False  True False  True False]


In [74]:
import numpy as np
arr = np.array([1,2,np.nan,4,np.nan,6])
print(np.isnan(arr))

print(np.nan == np.nan)

[False False  True False  True False]
False


In [75]:
# np.nan cannot be compared directly

In [77]:
#np.nan_to_num(array, nan=value) default=0
# returns a new array

import numpy as np
arr = np.array([1,2,np.nan,4,np.nan,6])
cleaned_arr = np.nan_to_num(arr, nan=100)
print(cleaned_arr)

[  1.   2. 100.   4. 100.   6.]


In [78]:
#np.isinf() , returns boolean value.
#1/0
import numpy as np
arr = np.array([1,2,np.inf,4,-np.inf,6])
print(arr)

[  1.   2.  inf   4. -inf   6.]


In [79]:
#np.isinf() 
#1/0
import numpy as np
arr = np.array([1,2,np.inf,4,-np.inf,6])
print(np.isinf(arr))

[False False  True False  True False]


In [80]:
# Replace Infinite Values with Finite Values
import numpy as np
arr = np.array([1,2,np.inf,4,-np.inf,6])
print(np.isinf(arr))
cleaned_arr = np.nan_to_num(arr, posinf=1000, neginf=1000)
print(cleaned_arr)

[False False  True False  True False]
[   1.    2. 1000.    4. 1000.    6.]
